version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=jobscraper
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_DATABASE: jobscraper
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A app.tasks.scraping_tasks worker --loglevel=info
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=jobscraper
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  celery-beat:
    build: .
    command: celery -A app.tasks.scraping_tasks beat --loglevel=info
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=jobscraper
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

volumes:
  mongodb_data:
